[package]
name = "vk-app"
version = "0.1.0"
authors = ["Markus Walther <m.walther97@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11"
vulkano-win = "0.11"
vulkano-shaders = "0.11"
winit = "0.18"
timer = "0.1.3"
chrono = "0.4.0"
time = "0.1"
